[rospy.client][INFO] 2017-08-14 08:36:40,459: init_node, name[/bebop/fence], pid[67]
[xmlrpc][INFO] 2017-08-14 08:36:40,459: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-08-14 08:36:40,460: Started XML-RPC server [http://ubuntu:44227/]
[rospy.init][INFO] 2017-08-14 08:36:40,461: ROS Slave URI: [http://ubuntu:44227/]
[rospy.impl.masterslave][INFO] 2017-08-14 08:36:40,461: _ready: http://ubuntu:44227/
[xmlrpc][INFO] 2017-08-14 08:36:40,463: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-08-14 08:36:40,463: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-08-14 08:36:40,562: registered with master
[rospy.rosout][INFO] 2017-08-14 08:36:40,562: initializing /rosout core topic
[rospy.rosout][INFO] 2017-08-14 08:36:40,565: connected to core topic /rosout
[rospy.simtime][INFO] 2017-08-14 08:36:40,567: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-08-14 08:36:40,644: topic[/bebop/stop] adding connection to [/bebop/path_follower], count 0
[rospy.internal][INFO] 2017-08-14 08:36:40,699: topic[/bebop/enable_tracking] adding connection to [http://ubuntu:42247/], count 0
[rospy.internal][INFO] 2017-08-14 08:36:40,700: topic[/bebop/target] adding connection to [http://ubuntu:39408/], count 0
[rospy.internal][INFO] 2017-08-14 08:36:40,701: topic[/bebop/des_vel] adding connection to [http://ubuntu:39408/], count 0
[rospy.internal][INFO] 2017-08-14 08:36:40,702: topic[/bebop/land] adding connection to [http://ubuntu:42247/], count 0
[rospy.internal][INFO] 2017-08-14 08:36:40,712: topic[/bebop/cmd_vel_input] adding connection to [http://ubuntu:42247/], count 0
[rospy.internal][INFO] 2017-08-14 08:36:40,712: topic[/bebop/land] adding connection to [http://ubuntu:44227/], count 1
[rospy.internal][INFO] 2017-08-14 08:36:40,711: topic[/bebop/takeoff_input] adding connection to [http://ubuntu:42247/], count 0
[rospy.internal][INFO] 2017-08-14 08:36:40,718: topic[/bebop/land] adding connection to [/bebop/fence], count 0
[rosout][INFO] 2017-08-14 08:36:40,723: Will start SimpleActionServer fence_control
[rosout][INFO] 2017-08-14 08:36:40,735: Started SimpleActionServer fence_control
[rospy.internal][INFO] 2017-08-14 08:36:40,854: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2017-08-14 08:36:41,057: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-08-14 08:36:41,068: Unable to initiate TCP/IP socket to ubuntu:39567 (http://ubuntu:42247/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:36:41,069: Unable to initiate TCP/IP socket to ubuntu:39567 (http://ubuntu:42247/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:36:41,069: Unable to initiate TCP/IP socket to ubuntu:39567 (http://ubuntu:42247/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:36:41,073: topic[/bebop/land] removing connection to /bebop/fence
[rospy.internal][ERROR] 2017-08-14 08:36:41,073: Unable to initiate TCP/IP socket to ubuntu:39567 (http://ubuntu:42247/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:36:41,074: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2017-08-14 08:36:41,074: Unable to initiate TCP/IP socket to ubuntu:46534 (http://ubuntu:44227/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:36:41,075: topic[/bebop/stop] removing connection to /bebop/path_follower
[rospy.internal][INFO] 2017-08-14 08:36:41,075: topic[/bebop/land] removing connection to http://ubuntu:42247/
[rospy.internal][INFO] 2017-08-14 08:36:41,076: topic[/bebop/land] removing connection to http://ubuntu:44227/
[rospy.internal][INFO] 2017-08-14 08:36:41,076: topic[/bebop/des_vel] removing connection to http://ubuntu:39408/
[rospy.internal][INFO] 2017-08-14 08:36:41,076: topic[/bebop/target] removing connection to http://ubuntu:39408/
[rospy.internal][INFO] 2017-08-14 08:36:41,076: topic[/bebop/takeoff_input] removing connection to http://ubuntu:42247/
[rospy.internal][INFO] 2017-08-14 08:36:41,077: topic[/bebop/cmd_vel_input] removing connection to http://ubuntu:42247/
[rospy.internal][INFO] 2017-08-14 08:36:41,077: topic[/bebop/enable_tracking] removing connection to http://ubuntu:42247/
[rospy.impl.masterslave][INFO] 2017-08-14 08:36:41,077: signal-2
[rospy.core][INFO] 2017-08-14 08:36:41,210: signal_shutdown [atexit]
[rospy.client][INFO] 2017-08-14 08:37:06,447: init_node, name[/bebop/fence], pid[66]
[xmlrpc][INFO] 2017-08-14 08:37:06,448: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-08-14 08:37:06,449: ROS Slave URI: [http://ubuntu:32847/]
[xmlrpc][INFO] 2017-08-14 08:37:06,449: Started XML-RPC server [http://ubuntu:32847/]
[rospy.impl.masterslave][INFO] 2017-08-14 08:37:06,450: _ready: http://ubuntu:32847/
[xmlrpc][INFO] 2017-08-14 08:37:06,450: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-08-14 08:37:06,451: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-08-14 08:37:06,550: registered with master
[rospy.rosout][INFO] 2017-08-14 08:37:06,550: initializing /rosout core topic
[rospy.rosout][INFO] 2017-08-14 08:37:06,553: connected to core topic /rosout
[rospy.simtime][INFO] 2017-08-14 08:37:06,555: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-08-14 08:37:06,642: topic[/bebop/stop] adding connection to [/bebop/path_follower], count 0
[rospy.internal][INFO] 2017-08-14 08:37:06,651: topic[/bebop/takeoff_input] adding connection to [http://ubuntu:34714/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:06,652: topic[/bebop/cmd_vel_input] adding connection to [http://ubuntu:34714/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:06,659: topic[/bebop/land] adding connection to [http://ubuntu:34714/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:06,663: topic[/bebop/land] adding connection to [http://ubuntu:32847/], count 1
[rospy.internal][INFO] 2017-08-14 08:37:06,666: topic[/bebop/land] adding connection to [/bebop/fence], count 0
[rospy.internal][INFO] 2017-08-14 08:37:06,669: topic[/bebop/target] adding connection to [http://ubuntu:43127/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:06,679: topic[/bebop/des_vel] adding connection to [http://ubuntu:43127/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:06,689: topic[/bebop/enable_tracking] adding connection to [http://ubuntu:34714/], count 0
[rosout][INFO] 2017-08-14 08:37:06,710: Will start SimpleActionServer fence_control
[rosout][INFO] 2017-08-14 08:37:06,722: Started SimpleActionServer fence_control
[rospy.internal][INFO] 2017-08-14 08:37:06,801: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2017-08-14 08:37:13,131: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-08-14 08:37:13,142: Unable to initiate TCP/IP socket to ubuntu:42509 (http://ubuntu:34714/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:37:13,142: Unable to initiate TCP/IP socket to ubuntu:42509 (http://ubuntu:34714/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:37:13,144: Unable to initiate TCP/IP socket to ubuntu:42509 (http://ubuntu:34714/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:37:13,145: Unable to initiate TCP/IP socket to ubuntu:42509 (http://ubuntu:34714/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:37:13,149: topic[/bebop/land] removing connection to /bebop/fence
[rospy.internal][ERROR] 2017-08-14 08:37:13,151: Unable to initiate TCP/IP socket to ubuntu:42061 (http://ubuntu:32847/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:37:13,151: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-08-14 08:37:13,153: topic[/bebop/stop] removing connection to /bebop/path_follower
[rospy.internal][INFO] 2017-08-14 08:37:13,153: topic[/bebop/land] removing connection to http://ubuntu:34714/
[rospy.internal][INFO] 2017-08-14 08:37:13,153: topic[/bebop/land] removing connection to http://ubuntu:32847/
[rospy.internal][INFO] 2017-08-14 08:37:13,154: topic[/bebop/des_vel] removing connection to http://ubuntu:43127/
[rospy.internal][INFO] 2017-08-14 08:37:13,155: topic[/bebop/target] removing connection to http://ubuntu:43127/
[rospy.internal][INFO] 2017-08-14 08:37:13,156: topic[/bebop/takeoff_input] removing connection to http://ubuntu:34714/
[rospy.internal][INFO] 2017-08-14 08:37:13,156: topic[/bebop/cmd_vel_input] removing connection to http://ubuntu:34714/
[rospy.internal][INFO] 2017-08-14 08:37:13,156: topic[/bebop/enable_tracking] removing connection to http://ubuntu:34714/
[rospy.impl.masterslave][INFO] 2017-08-14 08:37:13,157: signal-2
[rospy.client][INFO] 2017-08-14 08:37:45,710: init_node, name[/bebop/fence], pid[69]
[xmlrpc][INFO] 2017-08-14 08:37:45,710: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-08-14 08:37:45,711: Started XML-RPC server [http://ubuntu:46402/]
[rospy.init][INFO] 2017-08-14 08:37:45,711: ROS Slave URI: [http://ubuntu:46402/]
[rospy.impl.masterslave][INFO] 2017-08-14 08:37:45,712: _ready: http://ubuntu:46402/
[xmlrpc][INFO] 2017-08-14 08:37:45,713: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-08-14 08:37:45,714: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-08-14 08:37:45,812: registered with master
[rospy.rosout][INFO] 2017-08-14 08:37:45,813: initializing /rosout core topic
[rospy.rosout][INFO] 2017-08-14 08:37:45,815: connected to core topic /rosout
[rospy.simtime][INFO] 2017-08-14 08:37:45,817: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-08-14 08:37:45,898: topic[/bebop/stop] adding connection to [/bebop/path_follower], count 0
[rospy.internal][INFO] 2017-08-14 08:37:45,915: topic[/bebop/cmd_vel_input] adding connection to [http://ubuntu:32994/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:45,915: topic[/bebop/takeoff_input] adding connection to [http://ubuntu:32994/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:45,932: topic[/bebop/land] adding connection to [http://ubuntu:32994/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:45,934: topic[/bebop/land] adding connection to [http://ubuntu:46402/], count 1
[rospy.internal][INFO] 2017-08-14 08:37:45,936: topic[/bebop/land] adding connection to [/bebop/fence], count 0
[rospy.internal][INFO] 2017-08-14 08:37:45,944: topic[/bebop/target] adding connection to [http://ubuntu:45194/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:45,956: topic[/bebop/des_vel] adding connection to [http://ubuntu:45194/], count 0
[rospy.internal][INFO] 2017-08-14 08:37:45,958: topic[/bebop/enable_tracking] adding connection to [http://ubuntu:32994/], count 0
[rosout][INFO] 2017-08-14 08:37:45,975: Will start SimpleActionServer fence_control
[rosout][INFO] 2017-08-14 08:37:45,989: Started SimpleActionServer fence_control
[rospy.internal][INFO] 2017-08-14 08:37:46,191: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2017-08-14 08:38:09,126: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-08-14 08:38:09,135: Unable to initiate TCP/IP socket to ubuntu:46365 (http://ubuntu:32994/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:38:09,135: Unable to initiate TCP/IP socket to ubuntu:46365 (http://ubuntu:32994/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:38:09,136: Unable to initiate TCP/IP socket to ubuntu:46365 (http://ubuntu:32994/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:38:09,139: topic[/bebop/land] removing connection to /bebop/fence
[rospy.internal][INFO] 2017-08-14 08:38:09,140: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2017-08-14 08:38:09,140: Unable to initiate TCP/IP socket to ubuntu:37002 (http://ubuntu:46402/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-08-14 08:38:09,141: Unknown error initiating TCP/IP socket to ubuntu:46365 (http://ubuntu:32994/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-08-14 08:38:09,141: topic[/bebop/stop] removing connection to /bebop/path_follower
[rospy.internal][INFO] 2017-08-14 08:38:09,142: topic[/bebop/cmd_vel_input] removing connection to http://ubuntu:32994/
[rospy.internal][INFO] 2017-08-14 08:38:09,142: topic[/bebop/land] removing connection to http://ubuntu:32994/
[rospy.internal][INFO] 2017-08-14 08:38:09,143: topic[/bebop/land] removing connection to http://ubuntu:46402/
[rospy.internal][INFO] 2017-08-14 08:38:09,143: topic[/bebop/des_vel] removing connection to http://ubuntu:45194/
[rospy.internal][INFO] 2017-08-14 08:38:09,143: topic[/bebop/target] removing connection to http://ubuntu:45194/
[rospy.internal][INFO] 2017-08-14 08:38:09,143: topic[/bebop/takeoff_input] removing connection to http://ubuntu:32994/
[rospy.internal][INFO] 2017-08-14 08:38:09,144: topic[/bebop/enable_tracking] removing connection to http://ubuntu:32994/
[rospy.impl.masterslave][INFO] 2017-08-14 08:38:09,144: signal-2
[rospy.client][INFO] 2017-08-14 08:40:57,229: init_node, name[/bebop/fence], pid[71]
[xmlrpc][INFO] 2017-08-14 08:40:57,231: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-08-14 08:40:57,232: ROS Slave URI: [http://ubuntu:42888/]
[xmlrpc][INFO] 2017-08-14 08:40:57,232: Started XML-RPC server [http://ubuntu:42888/]
[rospy.impl.masterslave][INFO] 2017-08-14 08:40:57,233: _ready: http://ubuntu:42888/
[rospy.registration][INFO] 2017-08-14 08:40:57,236: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-08-14 08:40:57,236: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-08-14 08:40:57,333: registered with master
[rospy.rosout][INFO] 2017-08-14 08:40:57,334: initializing /rosout core topic
[rospy.rosout][INFO] 2017-08-14 08:40:57,336: connected to core topic /rosout
[rospy.simtime][INFO] 2017-08-14 08:40:57,338: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-08-14 08:40:57,391: topic[/bebop/stop] adding connection to [/bebop/path_follower], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,412: topic[/bebop/stop] adding connection to [/bebop/path_controller], count 1
[rospy.internal][INFO] 2017-08-14 08:40:57,434: topic[/bebop/cmd_vel_input] adding connection to [http://ubuntu:37466/], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,439: topic[/bebop/takeoff_input] adding connection to [http://ubuntu:37466/], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,445: topic[/bebop/land] adding connection to [http://ubuntu:37466/], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,447: topic[/bebop/land] adding connection to [http://ubuntu:42888/], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,449: topic[/bebop/land] adding connection to [/bebop/fence], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,459: topic[/bebop/target] adding connection to [http://ubuntu:34535/], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,467: topic[/bebop/des_vel] adding connection to [http://ubuntu:34535/], count 0
[rospy.internal][INFO] 2017-08-14 08:40:57,469: topic[/bebop/enable_tracking] adding connection to [http://ubuntu:37466/], count 0
[rosout][INFO] 2017-08-14 08:40:57,484: Will start SimpleActionServer fence_control
[rosout][INFO] 2017-08-14 08:40:57,496: Started SimpleActionServer fence_control
[rospy.internal][INFO] 2017-08-14 08:40:57,537: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2017-08-14 08:42:39,849: bad callback: <bound method Controller.has_received_desired_vel of <__main__.Controller object at 0x7f4f58d13b50>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/root/catkin_ws/src/drone_arena/scripts/fence_control.py", line 470, in has_received_desired_vel
    self.has_received_vel_in_world_frame(des_vel, des_omega)
  File "/root/catkin_ws/src/drone_arena/scripts/fence_control.py", line 452, in has_received_vel_in_world_frame
    self.update_desired_velocity(des_vel, des_omega)
  File "/root/catkin_ws/src/drone_arena/scripts/fence_control.py", line 479, in update_desired_velocity
    a_des = (v_des - np.array(self.velocity[:2])) / self.tau
AttributeError: 'Controller' object has no attribute 'velocity'

[rospy.core][INFO] 2017-08-14 08:49:48,928: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-08-14 08:49:48,942: Unable to initiate TCP/IP socket to ubuntu:34658 (http://ubuntu:37466/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:49:48,942: Unable to initiate TCP/IP socket to ubuntu:34658 (http://ubuntu:37466/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:49:48,945: Unable to initiate TCP/IP socket to ubuntu:34658 (http://ubuntu:37466/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:49:48,947: topic[/bebop/land] removing connection to /bebop/fence
[rospy.internal][ERROR] 2017-08-14 08:49:48,948: Unable to initiate TCP/IP socket to ubuntu:41245 (http://ubuntu:42888/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:49:48,949: Unable to initiate TCP/IP socket to ubuntu:34658 (http://ubuntu:37466/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:49:48,949: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-08-14 08:49:48,950: topic[/bebop/stop] removing connection to /bebop/path_follower
[rospy.internal][INFO] 2017-08-14 08:49:48,951: topic[/bebop/stop] removing connection to /bebop/path_controller
[rospy.internal][INFO] 2017-08-14 08:49:48,951: topic[/bebop/land] removing connection to http://ubuntu:37466/
[rospy.internal][INFO] 2017-08-14 08:49:48,952: topic[/bebop/land] removing connection to http://ubuntu:42888/
[rospy.internal][INFO] 2017-08-14 08:49:48,952: topic[/bebop/des_vel] removing connection to http://ubuntu:34535/
[rospy.internal][INFO] 2017-08-14 08:49:48,952: topic[/bebop/target] removing connection to http://ubuntu:34535/
[rospy.internal][INFO] 2017-08-14 08:49:48,953: topic[/bebop/takeoff_input] removing connection to http://ubuntu:37466/
[rospy.internal][INFO] 2017-08-14 08:49:48,953: topic[/bebop/cmd_vel_input] removing connection to http://ubuntu:37466/
[rospy.internal][INFO] 2017-08-14 08:49:48,953: topic[/bebop/enable_tracking] removing connection to http://ubuntu:37466/
[rospy.impl.masterslave][INFO] 2017-08-14 08:49:48,954: signal-2
[rospy.client][INFO] 2017-08-14 08:50:14,810: init_node, name[/bebop/fence], pid[67]
[xmlrpc][INFO] 2017-08-14 08:50:14,811: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-08-14 08:50:14,812: Started XML-RPC server [http://ubuntu:38948/]
[rospy.init][INFO] 2017-08-14 08:50:14,812: ROS Slave URI: [http://ubuntu:38948/]
[rospy.impl.masterslave][INFO] 2017-08-14 08:50:14,812: _ready: http://ubuntu:38948/
[xmlrpc][INFO] 2017-08-14 08:50:14,814: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-08-14 08:50:14,814: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-08-14 08:50:14,913: registered with master
[rospy.rosout][INFO] 2017-08-14 08:50:14,914: initializing /rosout core topic
[rospy.rosout][INFO] 2017-08-14 08:50:14,916: connected to core topic /rosout
[rospy.simtime][INFO] 2017-08-14 08:50:14,918: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-08-14 08:50:15,008: topic[/bebop/stop] adding connection to [/bebop/path_controller], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,010: topic[/bebop/stop] adding connection to [/bebop/path_follower], count 1
[rospy.internal][INFO] 2017-08-14 08:50:15,015: topic[/bebop/cmd_vel_input] adding connection to [http://ubuntu:44628/], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,019: topic[/bebop/takeoff_input] adding connection to [http://ubuntu:44628/], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,027: topic[/bebop/land] adding connection to [http://ubuntu:38948/], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,028: topic[/bebop/land] adding connection to [http://ubuntu:44628/], count 1
[rospy.internal][INFO] 2017-08-14 08:50:15,029: topic[/bebop/land] adding connection to [/bebop/fence], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,034: topic[/bebop/target] adding connection to [http://ubuntu:33380/], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,042: topic[/bebop/des_vel] adding connection to [http://ubuntu:33380/], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,046: topic[/bebop/enable_tracking] adding connection to [http://ubuntu:44628/], count 0
[rospy.internal][INFO] 2017-08-14 08:50:15,058: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2017-08-14 08:50:15,068: Will start SimpleActionServer fence_control
[rosout][INFO] 2017-08-14 08:50:15,080: Started SimpleActionServer fence_control
[rospy.core][INFO] 2017-08-14 08:50:35,835: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-08-14 08:50:35,848: Unable to initiate TCP/IP socket to ubuntu:35912 (http://ubuntu:44628/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:50:35,849: Unable to initiate TCP/IP socket to ubuntu:35912 (http://ubuntu:44628/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-08-14 08:50:35,852: Unable to initiate TCP/IP socket to ubuntu:35912 (http://ubuntu:44628/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:50:35,855: topic[/bebop/land] removing connection to /bebop/fence
[rospy.internal][ERROR] 2017-08-14 08:50:35,856: Unable to initiate TCP/IP socket to ubuntu:40367 (http://ubuntu:38948/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-08-14 08:50:35,856: topic[/rosout] removing connection to /rosout
[rospy.internal][WARNING] 2017-08-14 08:50:35,857: Unknown error initiating TCP/IP socket to ubuntu:35912 (http://ubuntu:44628/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 632, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-08-14 08:50:35,857: topic[/bebop/stop] removing connection to /bebop/path_controller
[rospy.internal][INFO] 2017-08-14 08:50:35,858: topic[/bebop/cmd_vel_input] removing connection to http://ubuntu:44628/
[rospy.internal][INFO] 2017-08-14 08:50:35,858: topic[/bebop/stop] removing connection to /bebop/path_follower
[rospy.internal][INFO] 2017-08-14 08:50:35,859: topic[/bebop/land] removing connection to http://ubuntu:38948/
[rospy.internal][INFO] 2017-08-14 08:50:35,859: topic[/bebop/land] removing connection to http://ubuntu:44628/
[rospy.internal][INFO] 2017-08-14 08:50:35,860: topic[/bebop/des_vel] removing connection to http://ubuntu:33380/
[rospy.internal][INFO] 2017-08-14 08:50:35,860: topic[/bebop/target] removing connection to http://ubuntu:33380/
[rospy.internal][INFO] 2017-08-14 08:50:35,860: topic[/bebop/takeoff_input] removing connection to http://ubuntu:44628/
[rospy.internal][INFO] 2017-08-14 08:50:35,860: topic[/bebop/enable_tracking] removing connection to http://ubuntu:44628/
[rospy.impl.masterslave][INFO] 2017-08-14 08:50:35,861: signal-2
[rospy.core][INFO] 2017-08-14 08:50:35,977: signal_shutdown [atexit]
