[roslaunch][INFO] 2017-08-14 09:05:05,723: Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2017-08-14 09:05:05,730: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2017-08-14 09:05:05,731: roslaunch starting with args ['/opt/ros/kinetic/bin/roslaunch', 'drone_arena', 'main.launch']
[roslaunch][INFO] 2017-08-14 09:05:05,731: roslaunch env is {'LANG': 'en_US.UTF-8', 'ROS_LOG_FILENAME': '/root/.ros/log/aa01d6a8-80cf-11e7-ac8a-001c42bad620/roslaunch-ubuntu-1.log', 'ROS_DISTRO': 'kinetic', 'SHLVL': '0', 'PYTHONPATH': '/root/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages', 'ROS_IP': '192.168.201.4', 'HOSTNAME': 'ubuntu', 'ROSLISP_PACKAGE_DIRECTORIES': '/root/catkin_ws/devel/share/common-lisp', 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'PWD': '/root/catkin_ws', 'ROS_MASTER_URI': 'http://192.168.201.36:11311', 'ROS_PACKAGE_PATH': '/root/catkin_ws/src/bebop_autonomy/bebop_autonomy:/root/catkin_ws/src/bebop_autonomy/bebop_description:/root/catkin_ws/src/bebop_autonomy/bebop_msgs:/root/catkin_ws/src/bebop_autonomy/bebop_driver:/root/catkin_ws/src/bebop_autonomy/bebop_tools:/root/catkin_ws/src/drone_arena:/root/catkin_ws/src/hl_navigation_msgs:/root/catkin_ws/src/ros-keyboard:/root/catkin_ws/src/lawa:/root/catkin_ws/src/optitrack_msgs:/root/catkin_ws/src/optitrack_odom:/opt/ros/kinetic/share', 'PKG_CONFIG_PATH': '/root/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig', 'PATH': '/opt/ros/kinetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'CMAKE_PREFIX_PATH': '/root/catkin_ws/devel:/opt/ros/kinetic', 'HOME': '/root', 'LD_LIBRARY_PATH': '/root/catkin_ws/devel/lib:/opt/ros/kinetic/lib'}
[roslaunch][INFO] 2017-08-14 09:05:05,731: starting in server mode
[roslaunch.parent][INFO] 2017-08-14 09:05:05,732: starting roslaunch parent run
[roslaunch][INFO] 2017-08-14 09:05:05,732: loading roscore config file /opt/ros/kinetic/etc/ros/roscore.xml
[roslaunch][INFO] 2017-08-14 09:05:05,813: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2017-08-14 09:05:05,814: loading config file /root/catkin_ws/src/drone_arena/launch/main.launch
[roslaunch][INFO] 2017-08-14 09:05:05,841: Added node of type [optitrack2odom/optitrack2odom] in namespace [/]
[roslaunch][INFO] 2017-08-14 09:05:05,845: Added node of type [drone_arena/fence_control.py] in namespace [/bebop/]
[roslaunch][INFO] 2017-08-14 09:05:05,885: Added node of type [joy/joy_node] in namespace [/bebop/]
[roslaunch][INFO] 2017-08-14 09:05:05,886: Added node of type [joy_teleop/joy_teleop.py] in namespace [/bebop/]
[roslaunch][INFO] 2017-08-14 09:05:05,887: Added node of type [drone_arena/diagnostics.py] in namespace [/bebop/]
[roslaunch][INFO] 2017-08-14 09:05:05,887: Added node of type [drone_arena/led.py] in namespace [/bebop/]
[roslaunch][INFO] 2017-08-14 09:05:05,888: ... selected machine [] for node of type [optitrack2odom/optitrack2odom]
[roslaunch][INFO] 2017-08-14 09:05:05,888: ... selected machine [] for node of type [drone_arena/fence_control.py]
[roslaunch][INFO] 2017-08-14 09:05:05,889: ... selected machine [] for node of type [joy/joy_node]
[roslaunch][INFO] 2017-08-14 09:05:05,889: ... selected machine [] for node of type [joy_teleop/joy_teleop.py]
[roslaunch][INFO] 2017-08-14 09:05:05,890: ... selected machine [] for node of type [drone_arena/diagnostics.py]
[roslaunch][INFO] 2017-08-14 09:05:05,890: ... selected machine [] for node of type [drone_arena/led.py]
[roslaunch.pmon][INFO] 2017-08-14 09:05:05,892: start_process_monitor: creating ProcessMonitor
[roslaunch.pmon][INFO] 2017-08-14 09:05:05,892: created process monitor <ProcessMonitor(ProcessMonitor-1, initial daemon)>
[roslaunch.pmon][INFO] 2017-08-14 09:05:05,893: start_process_monitor: ProcessMonitor started
[roslaunch.parent][INFO] 2017-08-14 09:05:05,893: starting parent XML-RPC server
[roslaunch.server][INFO] 2017-08-14 09:05:05,894: starting roslaunch XML-RPC server
[roslaunch.server][INFO] 2017-08-14 09:05:05,894: waiting for roslaunch XML-RPC server to initialize
[xmlrpc][INFO] 2017-08-14 09:05:05,894: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-08-14 09:05:05,895: Started XML-RPC server [http://192.168.201.4:38201/]
[xmlrpc][INFO] 2017-08-14 09:05:05,895: xml rpc node: starting XML-RPC server
[roslaunch.pmon][INFO] 2017-08-14 09:05:10,897: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, started daemon 140369902851840)>
[roslaunch.pmon][INFO] 2017-08-14 09:05:10,929: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 140369902851840)>
[roslaunch.pmon][INFO] 2017-08-14 09:05:10,930: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 140369902851840)>: remaining procs are []
[roslaunch.pmon][INFO] 2017-08-14 09:05:10,932: ProcessMonitor exit: cleaning up data structures and signals
[roslaunch.pmon][INFO] 2017-08-14 09:05:10,932: ProcessMonitor exit: pmon has shutdown
[roslaunch][ERROR] 2017-08-14 09:05:10,932: Unable to contact my own server at [http://192.168.201.4:38201/].
This usually means that the network is not configured properly.

A common cause is that the machine cannot ping itself.  Please check
for errors by running:

	ping 192.168.201.4

For more tips, please see

	http://www.ros.org/wiki/ROS/NetworkSetup

[roslaunch][ERROR] 2017-08-14 09:05:10,933: The traceback for the exception was written to the log file
[roslaunch][ERROR] 2017-08-14 09:05:10,935: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 226, in _start_infrastructure
    self._start_server()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 177, in _start_server
    self.server.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/server.py", line 405, in start
    """%(self.uri, p.hostname))
RLException: Unable to contact my own server at [http://192.168.201.4:38201/].
This usually means that the network is not configured properly.

A common cause is that the machine cannot ping itself.  Please check
for errors by running:

	ping 192.168.201.4

For more tips, please see

	http://www.ros.org/wiki/ROS/NetworkSetup


[rospy.core][INFO] 2017-08-14 09:05:10,936: signal_shutdown [atexit]
